### ISSUE TITLE
Mongo DB items limited to 50 rows

### ISSUE THREAD

**Issue by curtislisle** [ronichoudhury/nci-nanoparticles-vm#5]
I Have created two different mondo databases with 3200 and 415 rows, respectively.  However the Girder view in candela seems limited to 50 items.

**Comment by waxlamp** [comment]
@curtislisle, could you be more specific about what you're seeing? (I'm not sure what "Girder view in Candela" means.)

**Comment by curtislisle** [comment]
sorry I wasn’t clear.  I meant when ResLab is showing a girder_db_item, all elements in the dataset aren’t being shown, just the first 50.

When I open the nanoparticles.json, for example, and map it to UpSet in ResLab, the “Dataset information” grey box in the UpSet interface shows “Elements: 50” when there are actually  3270 elements in the mongo collection. 

A possible cause could be the mongo query returning with limit=50.

**Comment by waxlamp** [comment]
I had the same thought about the mongo query.

@alex-r-bigelow, is there an easy way to customize the `limit` parameter in this case?

**Comment by alex-r-bigelow** [comment]
Whoops! This was totally my bad. I've fixed it here: https://github.com/Kitware/candela/commit/671df6bdd60dc9793674a00c7b24366516d9ad5b

Should I branch / PR this repo as well?

**Comment by waxlamp** [comment]
This fix will allow the NCI demo to show all the data but setting `limit` to 0 doesn't seem like a viable permanent fix right? I just want to make sure that we'll generalize this via UI or something to make a true fix for Resonant Laboratory.

In the meantime, yes please do make a PR for this repo pointing to the fix.

**Comment by alex-r-bigelow** [comment]
Yes, absolutely—we're planning a filter-aware paging (+sampling?) interface that will do smarter things with `limit` and `offset`. But first we'll need to get the filters working :-)
